[build]
  command = "npm run build"  # أو yarn build
  publish = "dist"           # تأكد من أن المجلد الناتج عن البناء هو "dist"

[[headers]]
  # طبق هذه القاعدة على كل ملفات JS
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
